### ISSUE TITLE
Graphic export options

### ISSUE THREAD

**Issue by ymilesz** [sculab/RASP#2]
Hi Dr. Yu,

  I really like the implementation of various R packages and programs into one convenient GUI, and I was wondering if the graphic and legend can be edited in the program or does it have to be exported to SVG? 

Thanks,

Miles

**Comment by sculab** [comment]
Hi Miles,
You could export the graphic in emf format. It is a popular vector graphic format. You could paste the emf file in powerpoint and save it as pdf format. The Adobe Illustrator could also edit emf format.
Best wishes,
Yan

**Comment by ymilesz** [comment]
Will do, thank you!
